<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Dropdown</name>
   <tag></tag>
   <elementGuidId>9c622815-400a-428e-bf20-796a7d71ef73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.cds--table-expand > button.cds--table-expand__button > svg.cds--table-expand__svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::*[name()='svg'][3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>bce0f136-4a90-47ad-973d-df8d98efa9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06bd704f-ebd1-4581-b900-984b14e9298f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>xMidYMid meet</value>
      <webElementGuid>ddcb1070-ff80-41dd-8e27-b5426b809322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>fa2ae8a8-da0c-490a-9446-7053dd496048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>45c4b846-0990-49dc-901b-75b2bcded9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>121847a4-a0c6-4a32-8c17-34c1ad42d40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 16</value>
      <webElementGuid>8d8a2c18-1716-4b6f-bbe2-cdc898911e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f91af50-44a2-4574-abfb-34a8d206710d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cds--table-expand__svg</value>
      <webElementGuid>56a2bc39-eb68-44c8-8b72-ecfd48dca6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>1d9f960f-d836-4fdc-b16d-4e4e437f9b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@openmrs/esm-home-app-page-0&quot;)/main[@class=&quot;omrs-main-content&quot;]/div[@class=&quot;-esm-home__home-dashboard__homePageWrapper___ysEHx&quot;]/section[@class=&quot;-esm-home__home-dashboard__dashboardContainer___q4adH&quot;]/div[@class=&quot;-esm-home__dashboard-view__dashboardView___bKS9+&quot;]/div[3]/div[@class=&quot;-esm-home__home-page-widgets__homePageWidget___sQAOV&quot;]/div[2]/div[@class=&quot;-esm-appointments__home-appointments__container___uCU0X&quot;]/div[@class=&quot;cds--layer-two -esm-appointments__appointments-table__container___32+lN&quot;]/div[@class=&quot;cds--data-table-container&quot;]/div[@class=&quot;cds--data-table-content&quot;]/table[@class=&quot;cds--data-table cds--data-table--sm cds--data-table--sort cds--data-table--zebra cds--data-table--visible-overflow-menu&quot;]/tbody[1]/tr[@class=&quot;cds--parent-row&quot;]/td[@class=&quot;cds--table-expand&quot;]/button[@class=&quot;cds--table-expand__button&quot;]/svg[@class=&quot;cds--table-expand__svg&quot;]</value>
      <webElementGuid>2ebbe900-ae8d-471d-8c34-3a1263aab6ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>4270c4c9-feca-4f57-a84c-45b74242f253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to sort rows by Status header in ascending order'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>62c12db0-80e5-4b26-9fee-7ef683041d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Melissa Wright'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>a5dbde16-cbcd-4a23-b1ec-987bfebf6d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rehabilitation service'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>b974563b-64cb-41b0-b6ea-850bd71ca815</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
