<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Continue</name>
   <tag></tag>
   <elementGuidId>491a88dc-3e91-4ea8-89d7-b92ca28f6575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b7f2be5-40d0-4af2-86f2-8542494d0343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-esm-login__login__continueButton___VnN+0 cds--btn cds--btn--primary</value>
      <webElementGuid>3cf40a70-c3ee-4c22-af0e-5667aeb21ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a46133a8-9da3-438c-8fb2-f745ddf559c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>ad31de4f-889a-44ac-ade1-96dad7331d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@openmrs/esm-login-app-page-0&quot;)/div[@class=&quot;-esm-login__login__container___SmdkR&quot;]/div[@class=&quot;cds--tile -esm-login__login__loginCard___iiPcZ&quot;]/form[1]/div[@class=&quot;-esm-login__login__inputGroup___3yw2m&quot;]/button[@class=&quot;-esm-login__login__continueButton___VnN+0 cds--btn cds--btn--primary&quot;]</value>
      <webElementGuid>220deb51-93d4-43dd-9a4d-05bf2c441b5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>5be27a0c-71c3-4212-8b4d-04b24d68ce35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@openmrs/esm-login-app-page-0']/div/div/form/div/button</value>
      <webElementGuid>8cfa96c4-f44b-4f56-83ba-7bf94d4a4278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::button[1]</value>
      <webElementGuid>3a46bb24-e66b-4859-82ba-a87dd0217f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Built with'])[1]/preceding::button[1]</value>
      <webElementGuid>d908d6d6-62be-480b-bf4f-e416462af1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='An open-source medical record system and global community'])[1]/preceding::button[1]</value>
      <webElementGuid>be0ab815-7736-41b5-bfe6-ee12d14eaf62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>bafc229f-09ff-40cc-b690-864531095bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>09a0c3cd-a202-436f-9fa6-49ff602254bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>7c60cfc7-be9e-480e-b215-986aba71977b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
