<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_Home</name>
   <tag></tag>
   <elementGuidId>9ebad7ce-e98b-4edf-8e4a-99879b06731e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='single-spa-application:@openmrs/esm-home-app-page-0']/main/div/section/div[2]/div/div/div/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9a0b588d-8ce8-4e78-8717-0a7a68ee8f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>P5kBN-q2g2nkNYCgydQ1vg==</value>
      <webElementGuid>ae1715b9-2501-4187-9d3c-8b1ff7f66235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>c5ea641d-4bbf-4e94-b6bb-9265ed3d4210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@openmrs/esm-home-app-page-0&quot;)/main[@class=&quot;omrs-main-content&quot;]/div[@class=&quot;-esm-home__home-dashboard__homePageWrapper___ysEHx&quot;]/section[@class=&quot;-esm-home__home-dashboard__dashboardContainer___q4adH&quot;]/div[@class=&quot;-esm-home__dashboard-view__dashboardView___bKS9+&quot;]/div[1]/div[@class=&quot;dI4YgT2YE2J3goz60lkGTA== -esm-home__page-header__pageHeader___cndBa&quot;]/div[@class=&quot;JGea75oGL3rl8HguRCx48Q==&quot;]/div[@class=&quot;E6QoCxKy3JK7VOI-2yhNXA==&quot;]/p[@class=&quot;P5kBN-q2g2nkNYCgydQ1vg==&quot;]</value>
      <webElementGuid>22af675a-018a-4fd9-9c67-ceb6dd56b4a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@openmrs/esm-home-app-page-0']/main/div/section/div[2]/div/div/div/div/p[2]</value>
      <webElementGuid>2ab96649-aae8-408c-a6b1-7579e7d1eceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::p[2]</value>
      <webElementGuid>69dc958c-b3e5-4d24-a929-552e6091ce81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::p[2]</value>
      <webElementGuid>ab811a47-fec6-4b2d-93cc-5f3e0cdc5ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>5d0fe401-dc7f-46e1-aa71-7df5128f8761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>0307d47b-416d-4981-897b-216a9e7753cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
