<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_InvalidLogin</name>
   <tag></tag>
   <elementGuidId>d22b75a1-208b-44b1-9a95-3813cc867fcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cds--inline-notification__subtitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='single-spa-application:@openmrs/esm-login-app-page-0']/div/div/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34b22177-3d43-4a89-8a1c-1186857996bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cds--inline-notification__subtitle</value>
      <webElementGuid>b3be7ea2-d8f0-4146-83a6-70a496cc94cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid username or password</value>
      <webElementGuid>9e4f7cfc-74f8-4e1d-8fd9-f472f15bd3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@openmrs/esm-login-app-page-0&quot;)/div[@class=&quot;-esm-login__login__container___SmdkR&quot;]/div[@class=&quot;cds--tile -esm-login__login__loginCard___iiPcZ&quot;]/div[@class=&quot;-esm-login__login__errorMessage___ZcPMy&quot;]/div[@class=&quot;cds--inline-notification cds--inline-notification--error&quot;]/div[@class=&quot;cds--inline-notification__details&quot;]/div[@class=&quot;cds--inline-notification__text-wrapper&quot;]/div[@class=&quot;cds--inline-notification__subtitle&quot;]</value>
      <webElementGuid>93255fe8-0cd9-45bb-8391-daa1b6662209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@openmrs/esm-login-app-page-0']/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>60ab770c-5b57-4551-af5e-439a0f726489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::div[1]</value>
      <webElementGuid>dcd7ea20-c04e-4296-9df4-73f349e4af9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::div[2]</value>
      <webElementGuid>6864041e-a99e-4032-878f-4702bfceb861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::div[6]</value>
      <webElementGuid>cd778441-6e65-4621-8937-2a9906986c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid username or password']/parent::*</value>
      <webElementGuid>1714eca8-0c1a-4d8e-b78b-6f2f9dd15bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]</value>
      <webElementGuid>55e204a4-0097-4f0f-aca2-ef0bfe45f96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Invalid username or password' or . = 'Invalid username or password')]</value>
      <webElementGuid>967d8789-2032-4501-9146-3d3f4b4bd3fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
